import type { GuardConfig } from "./types.ts";

export const DEFAULT_CONFIG = {
	enabled: true,
	matchers: {
		bash: { param: "command", type: "bash" },
		read: { param: "path", type: "glob" },
		write: { param: "path", type: "glob" },
		edit: { param: "path", type: "glob" },
		grep: { param: "path", type: "glob" },
		find: { param: "path", type: "glob" },
		ls: { param: "path", type: "glob" },
	},
	rules: {
		bash: {
			"*": "ask",
			basename: "allow",
			cat: "allow",
			cd: "allow",
			column: "allow",
			cut: "allow",
			date: "allow",
			direnv: "allow",
			dirname: "allow",
			echo: "allow",
			env: "allow",
			expand: "allow",
			fd: "allow",
			file: "allow",
			find: "allow",
			fold: "allow",
			fmt: "allow",
			"gh issue list": "allow",
			"gh issue view": "allow",
			"gh pr diff": "allow",
			"gh pr list": "allow",
			"gh pr view": "allow",
			"gh repo view": "allow",
			"git blame": "allow",
			"git branch --show-current": "allow",
			"git diff": "allow",
			"git log": "allow",
			"git show": "allow",
			"git status": "allow",
			grep: "allow",
			head: "allow",
			hostname: "allow",
			id: "allow",
			jq: "allow",
			ls: "allow",
			"mcp-cli": "allow",
			md5sum: "allow",
			nix: "allow",
			nl: "allow",
			node: "allow",
			"npm test": "allow",
			"pnpm test": "allow",
			pwd: "allow",
			read: "allow",
			readlink: "allow",
			realpath: "allow",
			rev: "allow",
			rg: "allow",
			sed: "allow",
			"sed --in-place*": "ask",
			"sed -I*": "ask",
			"sed -i*": "ask",
			seq: "allow",
			shasum: "allow",
			sha256sum: "allow",
			shuf: "allow",
			sort: "allow",
			stat: "allow",
			tac: "allow",
			tail: "allow",
			tr: "allow",
			true: "allow",
			uname: "allow",
			unexpand: "allow",
			uniq: "allow",
			wc: "allow",
			which: "allow",
			whoami: "allow",
			xargs: "allow",
			yq: "allow",
		},
		// File tools are handled by pi-sandbox; guard defers to it by default.
		// Users without sandbox can override these in their settings.json.
		read: "allow",
		write: "allow",
		edit: "allow",
		grep: "allow",
		find: "allow",
		ls: "allow",
	},
} as const satisfies GuardConfig;
